name: Publish Python Package

on:
  push:
    branches: [main]
    # (recommended) publish only on tags:
    # tags: [ "v*" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build & Publish with Poetry
        uses: ./.github/actions/poetry-publish
        with:
          python-version: "3.11"
          pypi-token: ${{ secrets.PYPI_TOKEN }}
          run-tests: "true"
          pytest-args: "--ignore=tests/test_card_creator.py"
          publish: "true"
          no-venv: "true"
