name: Test Python Package

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - "feature/**"

jobs:
  test:
    name: "Test with uv"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Setup
        uses: ./.github/actions/setup-project

      - name: Run tests
        run: uv run pytest -v